// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoAHVmpLVjF0DGAjRygpax-4NWo8BaeYk',
    appId: '1:934744930336:web:c00f96af76ce005a04a445',
    messagingSenderId: '934744930336',
    projectId: 'fir-smkt',
    authDomain: 'fir-smkt.firebaseapp.com',
    storageBucket: 'fir-smkt.firebasestorage.app',
    measurementId: 'G-3B0GFPYH8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN1RiOeOHTnGO20PzEq2ZUpz2jOQ6-Yoc',
    appId: '1:934744930336:android:70106e642489e1a004a445',
    messagingSenderId: '934744930336',
    projectId: 'fir-smkt',
    storageBucket: 'fir-smkt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_gIYAkEorVRaekipmHn2NzLv9OwP3tmY',
    appId: '1:934744930336:ios:1c6536d048e4a54604a445',
    messagingSenderId: '934744930336',
    projectId: 'fir-smkt',
    storageBucket: 'fir-smkt.firebasestorage.app',
    iosBundleId: 'com.example.splitmarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_gIYAkEorVRaekipmHn2NzLv9OwP3tmY',
    appId: '1:934744930336:ios:1c6536d048e4a54604a445',
    messagingSenderId: '934744930336',
    projectId: 'fir-smkt',
    storageBucket: 'fir-smkt.firebasestorage.app',
    iosBundleId: 'com.example.splitmarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoAHVmpLVjF0DGAjRygpax-4NWo8BaeYk',
    appId: '1:934744930336:web:ac86547d5913e86604a445',
    messagingSenderId: '934744930336',
    projectId: 'fir-smkt',
    authDomain: 'fir-smkt.firebaseapp.com',
    storageBucket: 'fir-smkt.firebasestorage.app',
    measurementId: 'G-VPDZWG8X0L',
  );
}
