name: splitmarket
description: Aplicativo mobile para divisão de despesas em grupo.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  
  flutter:
    sdk: flutter

  file_picker: ^10.3.2
  
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2  # Versão mais recente compatível
  

  # Firebase - VERSÕES CORRETAS
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.3.0
  
  # Outras dependências
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.3
  provider: ^6.1.5+1
  http: ^1.2.1
  geolocator: ^12.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geocoding: ^3.0.0

  # Seleção de imagem/foto
  image_picker: ^1.1.2
  light: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
