name: splitmarket
description: Aplicativo mobile para divisão de despesas em grupo.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8

  sqflite: ^2.3.3
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.3

  #provider: ^6.1.2

  # Gerenciamento de estado
  provider: ^6.1.5+1

  # Requisições HTTP / APIs
  http: ^1.2.1

  # Mapas e localização
  geolocator: ^12.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # Seleção de imagem/foto
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/